version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled